### PR TITLE
Sprint 4 (#64)

### PR DESCRIPTION
**Pull request by yosuke65**

### CODE REVIEW

**Comment by calebpower** [comment]
What is this?

**Comment by yosuke65** [comment]
I tried to remove old and create new pull request.
Sorry Did I miss something?

**Comment by calebpower** [comment]
It appears as though you're merging the master branch into dev, and I'm confused as to why that's happening since the master branch should only contain code from Sprint 3. Unless I'm missing something, dev should contain everything that master has + the new changes. So, a merge from master would at best do nothing, and at worst undo changes.

But, I could be missing something.

**Comment by yosuke65** [comment]
Sorry for the confusion. What can I do for this?

**Comment by calebpower** [comment]
I was just wondering why the pull request was made... was just confused because it doesn't seem to include new code. If it was an accident, it can just be closed.

**Comment by yosuke65** [comment]
Okay I will close it. I don’t still fully understand the how pull request
work. I pushed new code after I made an old pull request so I thought I had
to create new pull request.

**Comment by calebpower** [comment]
ah yeah so what branch did you push new code to?

**Comment by yosuke65** [comment]
I believe it’s voting4 branch.

**Comment by yosuke65** [comment]
Sorry voting4 to dev branch. I always use version control and just click
push button so I created voting4 from dev branch I think it’s pushed to dev.

**Pull request closed without merging**
