### PR TITLE
Sprint 2

### PR DESCRIPTION
**Pull request by calebpower**

### CODE REVIEW

**Review by capple2016 — APPROVED** [review]
The views file could use some cleanup but other than that... I approve. Good job everybody!

**Comment by calebpower** [comment]
@capple2016 definitely agree. Perhaps we can split it up by different pages. I'll clean it up for Sprint 3.

**Comment by capple2016** [comment]
Let me know if you need any help!

**Comment by mbsim08** [comment]
Thank you for another great work and contribution

**Review by mbsim08 — APPROVED** [review]
Than you for another great work and contribution

**Comment by calebpower** [comment]
There's a preview of the `views.py` refactor at 3ce58ed. @capple2016

**Review by jakewaldrip — APPROVED** [review]
Looks great! Good work everybody!

**Review by ghost — APPROVED** [review]
Looks great to me!

**Review by yosuke65 — APPROVED** [review]

**Pull request merged**
